# Generated by Django 5.1.1 on 2024-09-05 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_learning', '0005_employee_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_learning.division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='in_scope',
            field=models.BooleanField(help_text='If the division is target for the             learning program, check this field.'),
        ),
    ]
